export const LOAD_ROUTE = 'LOAD_ROUTE';
export const ROUTE_LOADED = 'ROUTE_LOADED';

export const UPDATE_OPTIONS = 'UPDATE_OPTIONS';


export const LOAD_REPO_INFO = 'LOAD_REPO_INFO';
export const REPO_INFO_LOADED = 'REPO_INFO_LOADED';